### ISSUE TITLE
Compatability with ember-cli-compass-compiler

### ISSUE THREAD

**Issue by lessless** [artificialio/ember-cli-foundation-sass#19]
Hello! Thank you for the work the way you did is very convenient and if you find time please, make both this two great pieces of software work together - compass & foundation.

There is an error when this addon is used together with https://github.com/quaertym/ember-cli-compass-compiler
 
```javascript
directory tmp/compass_compiler-tmp_cache_dir-0ptms99l.tmp/assets
    error app/styles/app.scss (Line 58 of app/styles/_settings.scss: File to import not found or unreadable: foundation/functions.
Load paths:
  Compass::SpriteImporter
  /Users/lessless/tmp/asdad/app/styles
  /Users/lessless/.gem/ruby/2.1.4/gems/compass-core-1.0.3/stylesheets)
    write tmp/compass_compiler-tmp_cache_dir-0ptms99l.tmp/assets/asdad.css
Compilation failed in 1 files.

Command failed: 
Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by Globegitter** [comment]
Hmm, it is hard for me to tell why it is failing. Is there any reason you need compass and the latest node-sass 2.x is not enough?

**Comment by lessless** [comment]
compass is collection of mixins, they help to save time for designer.  It turned out that compass does sass compilation by itself https://github.com/quaertym/ember-cli-compass-compiler/issues/37

**Comment by holandes22** [comment]
Having the same issue here. Did you find a workaround to keep using ember-cli-compass-compiler?

**Comment by Globegitter** [comment]
By quickly looking at it again the issue seems to be that [ember-cli-sass](https://github.com/aexmachina/ember-cli-sass#usage) has an `includePaths` option. Which ensures that foundation can be imported. Does ember-cli-compass-compiler have a similar option?

IT seems https://github.com/quaertym/ember-cli-compass-compiler/issues/37#issuecomment-68347486 should do the trick.

**Comment by holandes22** [comment]
@Globegitter thank you! that did the trick.

I have this in my Brocfile:

```
var app = new EmberApp({
  'ember-cli-foundation-sass': {
    'foundationJs': true
  },
  compassOptions: {
    outputStyle: 'expanded',
    importPath: [
      'bower_components/foundation/scss/'
    ]
  }
});
